Repository AgileVentures/WebsiteOne, pull requests merged in 2018-08, with the labels that each got.

#2315 RSVPping AV events
  app/assets/javascripts/events.js
  app/assets/javascripts/events/show_event.js
  app/controllers/events_controller.rb
  app/views/events/show.html.erb
  config/routes.rb
  db/migrate/20180730173345_add_creator_attendance_to_events.rb
  db/schema.rb
  features/events/rsvping_event.feature
  features/step_definitions/basic_steps.rb
  features/step_definitions/event_steps.rb
Labels: in progress, please check

#2514 2503 refactor connections feature
  app/models/project.rb
  app/views/projects/_connections.html.erb
  features/projects/connections.feature
  features/projects/create_projects.feature
  features/projects/edit_project.feature
  features/projects/show_project.feature
  features/step_definitions/projects_steps.rb
Labels: in progress

#2511 Install node dependencies, add docker instructions
  Dockerfile
  config/initializers/airbrake.rb
  docker-compose.yml
  docker/README.md
  docker/config/database.yml
  docker/setup.sh
  docker/start.sh
  docker/stop.sh
  docs/project_setup.md
  package.json
Labels: in progress

#2520 Remove db host from database.yml
  config/database.yml
Labels: in progress

#2519 [WIP] rough draft of manipulating premium sponsor levels to
  app/controllers/subscriptions_controller.rb
  app/controllers/users_controller.rb
  app/views/users/profile/_set_level.html.erb
  app/views/users/profile/_summary.html.erb
  config/database.yml
  config/environments/development.rb
  config/settings/development.yml
  config/settings/test.yml
  features/premium/downgrade_membership.feature
  features/step_definitions/user_steps.rb
  features/support/helpers.rb
Labels: in progress

#2560 Fix forwarding domain for dashboard
  app/views/av_dashboard_tokens/create.html.erb
Labels: in progress

#2547 add other karma breakdown elements to karma table
  app/services/karma_calculator.rb
  db/migrate/20180810180605_add_karma_breakdown_elements_to_karma_table.rb
  db/schema.rb
  lib/tasks/scheduler.rake
  spec/services/karma_calculator_spec.rb
Labels: in progress

#2564 Add basic docs for setting up av dashboard token endpoint and giving access
  docs/how_to_setup_av_dashboard_token_endpoint.md
Labels: ready

#2570 quick defence against absence of existing subscription
  app/views/users/profile/_set_level.html.erb
Labels: in progress

#2543 Change join event button styles
  app/views/events/show.html.erb
  features/hangouts/hangout.feature
  features/step_definitions/event_steps.rb
  features/step_definitions/hangout_steps.rb
Labels: in progress

#2539 Search by programming language
  Gemfile
  Gemfile.lock
  app/assets/javascripts/projects.js
  app/assets/stylesheets/global/projects.scss
  app/controllers/projects_controller.rb
  app/jobs/github_languages_job.rb
  app/models/language.rb
  app/models/language_project.rb
  app/models/project.rb
  app/views/projects/index.html.erb
  config/initializers/simple_form.rb
  config/initializers/simple_form_bootstrap.rb
  config/locales/simple_form.en.yml
  db/migrate/20180813125658_create_languages.rb
  db/schema.rb
  features/devops/github_languages.feature
  features/projects/search_projects.feature
  features/step_definitions/basic_steps.rb
  features/step_definitions/devops_steps.rb
  features/step_definitions/projects_steps.rb
  lib/tasks/scheduler.rake
  lib/templates/erb/scaffold/_form.html.erb
  spec/models/language_project_spec.rb
Labels: in progress

#2587 add www prefix
  config/settings/production.yml
Labels: in progress

#2601 Move to headless chromedriver
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: in progress
