Repository AgileVentures/WebsiteOne, pull requests merged in 2018-10, with the labels that each got.

#2544 Add infinite scroll functionality, change tests
  app/assets/javascripts/application.js
  app/assets/javascripts/event_instances.js
  app/assets/javascripts/projects.js
  app/assets/javascripts/users.js
  app/assets/stylesheets/global/projects.scss
  app/views/projects/_listing.html.erb
  app/views/projects/index.html.erb
  app/views/projects/index.js.erb
  app/views/users/_user_list.html.erb
  app/views/users/index.html.erb
  app/views/users/index.js.erb
  features/projects/list_projects.feature
  features/projects/search_projects.feature
  features/step_definitions/basic_steps.rb
  features/users/user_list.feature
Labels: in progress

#2579 Join button for Mob events visible to PremiumMob members and up
  app/assets/javascripts/dashboard.js
  app/helpers/event_helper.rb
  app/models/event.rb
  app/models/user.rb
  app/views/events/show.html.erb
  app/views/visitors/_text_and_image_trail.html.erb
  db/seeds.rb
  features/events/edit_future_event.feature
  features/events/event_countdown.feature
  features/events/private_events.feature
  features/step_definitions/basic_steps.rb
  features/step_definitions/event_steps.rb
  features/step_definitions/user_steps.rb
  features/users/sign_in.feature
Labels: in progress

#2671 Updated docker setup README file fixes #2617
  docker/README.md
Labels: in progress

#2625 ensure paying users can navigate to update their card details
  app/views/application/_edit_card.html.erb
  app/views/cards/edit.html.erb
  app/views/users/profile/_summary.html.erb
  features/step_definitions/user_steps.rb
  features/users/profile_update_credit_card.feature
Labels: in progress

#2702 Test for bug and fix it
  app/views/events/show.html.erb
  features/events/start_event.feature
Labels: please check, ready

#2707 ensure only Premium Mob members and above can see mob event join buttons
  app/helpers/event_helper.rb
  app/services/slack_service.rb
  features/events/private_events.feature
  features/step_definitions/user_steps.rb
Labels: in progress

#2678 2612 refactor class method to scope
  app/controllers/projects_controller.rb
  app/models/project.rb
Labels: in progress

#2713 Issue#2690 filter Github secrets from VCR cassettes
  features/devops/github_commits.feature
  features/devops/github_last_updates.feature
  features/support/fixtures/cassettes/Update_github_languages_field_of_all_projects/Update_language_field_of_all_projects_with_valid_github_url.yml
  features/support/fixtures/cassettes/Update_github_last_update_field_of_all_projects/Update_last_update_field_of_all_projects_with_valid_github_url.yml
  features/support/fixtures/cassettes/Update_github_pitch_of_all_projects/Update_github_pitch_for_all_projects_with_valid_github_url.yml
  features/support/fixtures/cassettes/Update_github_stats_of_all_projects/Update_github_commit_count_of_all_projects_with_valid_github_url.yml
  features/support/vcr.rb
Labels: in progress

#2714 Update ubuntu_14.04_manual_install_notes
  docs/c9/install_notes.md
  docs/ubuntu/ubuntu_14.04_manual_install_notes.md
Labels: in progress

#2711 refactor cucumber sponsors banners
  features/pages.feature
  features/step_definitions/pages_steps.rb
Labels: in progress

#2700 Better spacing between embedded video and video links
  app/assets/stylesheets/application.scss
Labels: in progress

#2658 Make entire hovered home page circles clickable
  app/views/layouts/_round_banners.html.erb
Labels: in progress

#2698 Update rubocop.yml to latest release
  .rubocop.yml
Labels: in progress

#2642 Refactor GitHub languages job
  app/jobs/github_languages_job.rb
Labels: help wanted, in progress

#2719 Add intermittent failing test tag
  features/users/sign_in.feature
Labels: in progress

#2710 premium mob events should not ping public channels
  app/models/event_instance.rb
  app/services/slack_service.rb
  app/views/events/show.html.erb
  features/events/private_events.feature
  features/step_definitions/hangout_steps.rb
  spec/services/slack_service_spec.rb
Labels: in progress

#2727 Add link to upgrade on premium mob events, test
  app/views/events/show.html.erb
  features/events/private_events.feature
  features/step_definitions/basic_steps.rb
Labels: in progress

#2729 [WIP][docker]gems version checking and updating
  Dockerfile
  docker-compose.yml
  docker-entrypoint.sh
Labels: in progress

#2743 Removed rack-timeout from development env, fixes 2686
  Gemfile
  Gemfile.lock
Labels: in progress

#2726 Make event drop down show only active projects
  app/controllers/users_controller.rb
  features/step_definitions/event_steps.rb
  features/users/user_list.feature
Labels: in progress

#2772 add possibility to download events as calendar file
  Gemfile
  Gemfile.lock
  app/controllers/calendar_controller.rb
  app/views/events/index.html.erb
  config/routes.rb
  features/events/upcoming_events.feature
  features/step_definitions/basic_steps.rb
  spec/controllers/calendar_controller_spec.rb
Labels: in progress, ready

#2763 Update readme
  docs/development_environment_set_up.md
  docs/project_setup.md
Labels: in progress
